-- Pretty-Printed using HW2 Pretty-Printer 1.27 by Mikail.
PersistantData = 
{
	StrikeGroups = {},
	Squadrons = 
	{
		{
			type = "Vgr_MotherShip",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
		},
		{
			type = "Vgr_Carrier",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 1,
		},
		{
			type = "Vgr_Shipyard",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 1,
		},
		{
			type = "Vgr_ResourceCollector",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 6,
		},
		{
			type = "Vgr_ResourceController",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_Probe",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_Probe_ECM",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_Probe_Prox",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_HyperSpace_Platform",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_WeaponPlatform_Gun",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_WeaponPlatform_Missile",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_Scout",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_Interceptor",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 4,
		},
		{
			type = "Vgr_Bomber",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 4,
		},
		{
			type = "Vgr_LanceFighter",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 4,
		},
		{
			type = "Vgr_CommandCorvette",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
		{
			type = "Vgr_LaserCorvette",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 3,
		},
		{
			type = "Vgr_MinelayerCorvette",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 2,
		},
		{
			type = "Vgr_MissileCorvette",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 3,
		},
		{
			type = "Vgr_AssaultFrigate",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 6,
		},
		{
			type = "Vgr_HeavyMissileFrigate",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 6,
		},
		{
			type = "Vgr_InfiltratorFrigate",
			subsystems = {},
			shiphold = {},
			name = "",
			size = 1,
			number = 2,
		},
		{
			type = "Vgr_Destroyer",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 3,
		},
		{
			type = "Vgr_Battlecruiser",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
--		{
--			type = "Vgr_CommStation",
--			subsystems = {},
--			shiphold = {},
--			name = "",
--			number = 1,
--		},
--		{
--			type = "Vgr_PrisonStation",
--			subsystems = {},
--			shiphold = {},
--			name = "",
--			number = 1,
--		},
--		{
--			type = "Vgr_Planetkiller",
--			subsystems = {},
--			shiphold = {},
--			name = "",
--			number = 1,
--		},
		{
			type = "Vgr_PlanetkillerMissile",
			subsystems = {},
			shiphold = {},
			name = "",
			number = 2,
		},
	},
	Research = {},
}
